exp_settings:
  put_on_mega: False
  stop_instance_after_run: False
  send_discord_message: False
  seed: 3
  exp_name: 'exp_1'
  save_all_iterations: False 
  device: 'cpu'

img_settings:
  size: [40,20]
  width:  40 #960
  height:  20 #540
  model_type: 'vqgan'
  model: "vqgan_imagenet_f16_16384"

sequence_settings:
  initial_fps: 6
  max_frames: 3
  iterations_per_frame: "0: 1, 1: 1, 2:1, 109:2, 110:3,  111: 3, 112: 3, 198:3, 199:30, 200: 3, 270:3"
  text_prompts: "'Highly detailed photograph of a chess board in ancient greece with digital chess pieces': { 0: 1, 90:1, 110: 0 }, 'Intricate pokemon video game': { 0: 1, 90:1, 110: 0  },
              'Orcas in a spaceship towards the moon': { 0: 0, 90:0, 110: 1, 190: 1, 200:0 }, 'Cartoon': { 0: 0, 90:0, 110: 1, 190: 1, 200:0 },
              'Orcas on the moon': { 0: 0,  190: 0, 200:1 }, 'Artstation': {0: 0,  190: 0, 200:1 }"
  target_images: ""
  translation_x: "3"
  translation_y: "3"
  angle: "2"
  zoom_scale_factor: 0.25
  zoom_instrument: "kick"
  min_zoom: 1 
  max_zoom: 1.1
  its_min: 1 
  its_max: 1

super_res_settings:
  do_super_res: True
  upscale_factor: 4
  SRModel: 'SwinIR'
  batch_size: 4

slowmo_settings:
  do_slowmo: True
  target_fps: 12
  slowmo_factor: 4
