exp_settings:
  seed: 3
  exp_name: 'exp_1'
  save_all_iterations: False 
  device: 'cuda'

img_settings:
  size: [512,512]
  model_type: 'stable_diffusion' #stable_diffusion or vqgan
  model: "vqgan_imagenet_f16_16384"

sequence_settings:
  mode: interpolation
  initial_fps: 6
  max_frames: 5
  iterations_per_frame: "0: 10, 1: 10, 2:10, 109:10, 110:3,  111: 3, 112: 3, 198:3, 199:30, 200: 3, 270:3"
  # text_prompts: "'tall rectangular black monolith, monkeys in the desert looking at a large tall monolith, a detailed matte painting by Wes Anderson, behance, light and space, reimagined by industrial light and magic, matte painting, criterion collection': { 0: 1, 20:0},
  #             'tall rectangular black monolith, monkeys astronaut in the desert looking at a large tall monolith, a detailed matte painting by Wes Anderson, behance, light and space, reimagined by industrial light and magic, matte painting, criterion collection': { 0: 0, 20:1 },
  #             'a tall black spaceship lifting off the desert, a detailed matte painting by Wes Anderson, behance, light and space, reimagined by industrial light and magic, matte painting, criterion collection': { 20: 0,  40: 1}"
  text_prompts: "'dog': { 0: 1, 20:0},
               'cat': { 0: 0, 20:1 },
               'horse': { 20: 0,  40: 1}"
  prompt_strength: 0.9
  guidance_scale: 7.5
  num_inference_steps: 50
  zoom_scale_factor: 0.25
  zoom_instrument: "kick"
  its_min: 2
  its_max: 3

super_res_settings:
  do_super_res: False
  upscale_factor: 4
  SRModel: 'SwinIR'
  batch_size: 1

slowmo_settings:
  do_slowmo: True
  target_fps: 12
  slowmo_factor: 4
